name: 'swiftlane'
description: '在github模拟器上使用swift版本fastlane，实现对iOS自动化集成开发'
inputs:
  argOne:  # id of input
    description: '编译swiftlane'
    required: false
    default: ''
outputs:
  swiftlane-hash:
    description: "swiftlane-hash"
    value: ${{ steps.swiftlane-hash.outputs.swifthash }}
runs:
  using: "composite"  #Required You must set this value to 'composite'.
  steps:
    - id: swiftlane-hash
      run: |
        #在/work/_actions/中的库源码，不是git库，无法使用hashFiles()获取到git的hash值。
        # hash=$(git rev-parse --short HEAD)
        #echo hhh: $hash
        echo +++++++ ${{ hashFiles('./**/Package.resolved') }}
        echo "swifthash=${{ hashFiles('**/Package.resolved') }}" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ github.action_path }}
    - if: ${{ inputs.argOne == 'build' }}
      shell: bash
      run: |
        #/Users/runner/work/_actions/it-boyer/iFastlane/main
        cd ${{ github.action_path }} #$GITHUB_ACTION_PATH/script.sh
        brew bundle
        swift build -v
        ln -sf .build/debug/Runner swifttlane
        echo "${{ github.action_path }}" >> $GITHUB_PATH #写入环境变量，便于外部调用改action目下的可执行文件
