#https://augmentedcode.io/2021/04/26/running-tests-in-swift-package-with-github-actions/
name: swiftlane自测
# 触发条件
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
# 执行的任务
jobs:
  unit_tests:
    runs-on: macos-latest
    steps:
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.18.0
    - name: Repository checkout
      uses: actions/checkout@v2
    # 暂存
    - name: 执行swift-spm暂存操作
      uses: actions/cache@v3
      with:
        path: .build  #暂存项目内容
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - if: ${{ steps.cache-hello.outputs.cache-hit != 'true' }}
      name: Build for macOS
      run: swift build -v
    # - name: Lint
      # run: swiftlint
    - name: 安装brew插件
      run: brew bundle
      #测试lane
    - name: 测试hello world
      run: .build/debug/Runner lane hello name hsg say hahha

    # - name: Build for iOS
      # run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme IndexedDataStore -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
    # - name: Run iOS tests
      # run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme IndexedDataStore -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
